enum ActionTypes {
  // GET_ALL
  GET_ALL_MEETUPS = 'GET_ALL_MEETUPS',
  GET_ALL_MEETUPS_FAILURE = 'GET_ALL_MEETUPS_FAILURE',
  GET_ALL_MEETUPS_SUCCESS = 'GET_ALL_MEETUPS_SUCCESS',
  // CREATE_NEW
  CREATE_NEW_MEETUP = 'CREATE_NEW_MEETUP',
  CREATE_NEW_MEETUP_FAILURE = 'CREATE_NEW_MEETUP_FAILURE',
  CREATE_NEW_MEETUP_SUCCESS = 'CREATE_NEW_MEETUP_SUCCESS',
}

export default ActionTypes;
